# Generated by Django 6.0.6 on 2026-06-25 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('risk_score', models.IntegerField(default=0, help_text='0 = sin riesgo, 100 = máximo riesgo')),
                ('risky_clauses', models.JSONField(blank=True, default=list)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_interval_days', models.PositiveIntegerField(default=30, help_text='Días máximos sin check-in antes de activar el trigger')),
                ('last_check_in', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_action', models.CharField(choices=[('NOTIFY', 'Notificar por correo'), ('TRANSFER', 'Transferir documento'), ('PUBLISH', 'Publicar documento')], default='NOTIFY', max_length=50)),
                ('trigger_data', models.JSONField(blank=True, default=dict)),
                ('grace_period_days', models.PositiveIntegerField(default=7, help_text='Días de gracia después del vencimiento antes de ejecutar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='core.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.contracttrigger')),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
    ]
