# Generated by Django 6.0.6 on 2026-06-25 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_signature_geo_verified_signature_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WitnessSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('witness_email', models.EmailField(help_text='Email del testigo', max_length=254)),
                ('witness_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'En curso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20)),
                ('witness_notes', models.TextField(blank=True, help_text='Notas del testigo sobre la verificación')),
                ('identity_confirmed', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('room_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witness_sessions', to='core.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witness_sessions_as_owner', to=settings.AUTH_USER_MODEL)),
                ('witness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witness_sessions_as_witness', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
